development:
  adapter: mysql2
  encoding: utf8
  database: newcru
  pool: 5
  username: newcru_rw
  password: hoqzfyY.vQcAxeDTNEv?6wY
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: newcru_test
  pool: 5
  username: newcru_rw
  password: hoqzfyY.vQcAxeDTNEv?6wY
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: newcru_production
  pool: 5
  username: newcru_rw
  password: hoqzfyY.vQcAxeDTNEv?6wY
  socket: /tmp/mysql.sock
